const productSeedsPart3 = [
  {
    name: 'Microsoft Surface Laptop 4',
    description: 'Sleek and powerful laptop with touchscreen and Windows 10.',
    price: 1299,
    category: 'computers',
    image: 'https://cdn.vox-cdn.com/thumbor/1Q6q6q6q6q6q6q6q6q6q6q6q6q6=/0x0:2040x1360/1200x800/filters:focal(857x517:1183x843)/cdn.vox-cdn.com/uploads/chorus_image/image/70112345/microsoft_surface_laptop_4_1.0.jpg',
    brand: 'Microsoft',
    stock: 50,
  },
  {
    name: 'HP Envy 13',
    description: 'Lightweight laptop with 11th Gen Intel processor and long battery life.',
    price: 999,
    category: 'computers',
    image: 'https://cdn.hp.com/envy-13.jpg',
    brand: 'HP',
    stock: 40,
  },
  {
    name: 'Asus ROG Zephyrus G14',
    description: 'Gaming laptop with powerful AMD Ryzen processor and RTX graphics.',
    price: 1499,
    category: 'computers',
    image: 'https://cdn.asus.com/rog-zephyrus-g14.jpg',
    brand: 'Asus',
    stock: 30,
  },
  {
    name: 'Lenovo ThinkPad X1 Carbon',
    description: 'Business laptop with durable design and excellent keyboard.',
    price: 1399,
    category: 'computers',
    image: 'https://cdn.lenovo.com/thinkpad-x1-carbon.jpg',
    brand: 'Lenovo',
    stock: 35,
  },
  {
    name: 'Panasonic Lumix GH5',
    description: 'Mirrorless camera with 4K video and advanced image stabilization.',
    price: 1299,
    category: 'cameras',
    image: 'https://cdn.panasonic.com/lumix-gh5.jpg',
    brand: 'Panasonic',
    stock: 20,
  },
  {
    name: 'Canon PowerShot G7 X Mark III',
    description: 'Compact camera with 4K video and fast autofocus.',
    price: 749,
    category: 'cameras',
    image: 'https://cdn.canon.com/powershot-g7x.jpg',
    brand: 'Canon',
    stock: 25,
  },
  {
    name: 'Samsung Galaxy Watch 4',
    description: 'Smartwatch with health tracking and long battery life.',
    price: 249,
    category: 'electronics',
    image: 'https://images.samsung.com/is/image/samsung/p6pim/in/galaxy-watch4/gallery/in-galaxy-watch4-sm-r870-410397-sm-r870nzkainu-530462973?$720_576_PNG$',
    brand: 'Samsung',
    stock: 100,
  },
  {
    name: 'Apple AirPods Pro',
    description: 'Wireless earbuds with active noise cancellation and transparency mode.',
    price: 249,
    category: 'audio-video',
    image: 'https://cdn.apple.com/airpods-pro.jpg',
    brand: 'Apple',
    stock: 150,
  },
  {
    name: 'Bose SoundLink Revolve',
    description: 'Portable Bluetooth speaker with 360-degree sound.',
    price: 199,
    category: 'audio-video',
    image: 'https://cdn.bose.com/soundlink-revolve.jpg',
    brand: 'Bose',
    stock: 80,
  },
  {
    name: 'JBL Flip 5',
    description: 'Waterproof portable Bluetooth speaker with powerful sound.',
    price: 99,
    category: 'audio-video',
    image: 'https://cdn.jbl.com/flip-5.jpg',
    brand: 'JBL',
    stock: 120,
  },
  // 90 more unique products here...
];

module.exports = productSeedsPart3;
