const productSeedsPart4 = [
  {
    name: 'Nintendo Switch OLED',
    description: 'Portable gaming console with vibrant OLED display.',
    price: 349,
    category: 'gaming',
    image: 'https://cdn.nintendo.com/switch-oled.jpg',
    brand: 'Nintendo',
    stock: 80,
  },
  {
    name: 'Sony PlayStation 5',
    description: 'Next-gen gaming console with ultra-fast SSD and ray tracing.',
    price: 499,
    category: 'gaming',
    image: 'https://cdn.sony.com/ps5.jpg',
    brand: 'Sony',
    stock: 50,
  },
  {
    name: 'Xbox Series X',
    description: 'Powerful gaming console with 4K gaming and fast load times.',
    price: 499,
    category: 'gaming',
    image: 'https://cdn.xbox.com/series-x.jpg',
    brand: 'Microsoft',
    stock: 60,
  },
  {
    name: 'Logitech MX Master 3',
    description: 'Advanced wireless mouse with ergonomic design.',
    price: 99,
    category: 'computers',
    image: 'https://cdn.logitech.com/mx-master-3.jpg',
    brand: 'Logitech',
    stock: 150,
  },
  {
    name: 'Razer BlackWidow V3',
    description: 'Mechanical gaming keyboard with customizable RGB lighting.',
    price: 139,
    category: 'computers',
    image: 'https://cdn.razer.com/blackwidow-v3.jpg',
    brand: 'Razer',
    stock: 100,
  },
  {
    name: 'Corsair K95 RGB Platinum',
    description: 'High-performance mechanical keyboard with dedicated macro keys.',
    price: 199,
    category: 'computers',
    image: 'https://cdn.corsair.com/k95-rgb-platinum.jpg',
    brand: 'Corsair',
    stock: 80,
  },
  {
    name: 'Samsung T7 Portable SSD 1TB',
    description: 'Fast and compact external SSD with USB 3.2 Gen 2.',
    price: 169,
    category: 'computers',
    image: 'https://cdn.samsung.com/t7-ssd.jpg',
    brand: 'Samsung',
    stock: 120,
  },
  {
    name: 'Seagate Backup Plus Slim 2TB',
    description: 'Portable external hard drive with USB 3.0.',
    price: 59,
    category: 'computers',
    image: 'https://cdn.seagate.com/backup-plus-slim.jpg',
    brand: 'Seagate',
    stock: 140,
  },
  {
    name: 'Canon PIXMA TS9120 Printer',
    description: 'All-in-one wireless inkjet printer with scanning and copying.',
    price: 149,
    category: 'computers',
    image: 'https://cdn.canon.com/pixma-ts9120.jpg',
    brand: 'Canon',
    stock: 70,
  },
  {
    name: 'Epson EcoTank ET-4760',
    description: 'Wireless all-in-one printer with refillable ink tanks.',
    price: 399,
    category: 'computers',
    image: 'https://cdn.epson.com/ecotank-et4760.jpg',
    brand: 'Epson',
    stock: 60,
  },
  // 90 more unique products here...
];

module.exports = productSeedsPart4;
