const productSeedsPart5 = [
  {
    name: 'Fitbit Charge 5',
    description: 'Advanced fitness tracker with built-in GPS and heart rate monitoring.',
    price: 179,
    category: 'electronics',
    image: 'https://cdn.fitbit.com/charge5.jpg',
    brand: 'Fitbit',
    stock: 100,
  },
  {
    name: 'Garmin Forerunner 245',
    description: 'GPS running watch with advanced training features.',
    price: 299,
    category: 'electronics',
    image: 'https://cdn.garmin.com/forerunner245.jpg',
    brand: 'Garmin',
    stock: 80,
  },
  {
    name: 'KitchenAid Stand Mixer',
    description: 'Powerful stand mixer with multiple attachments.',
    price: 399,
    category: 'home-appliances',
    image: 'https://cdn.kitchenaid.com/stand-mixer.jpg',
    brand: 'KitchenAid',
    stock: 50,
  },
  {
    name: 'Instant Pot Duo 7-in-1',
    description: 'Multi-use programmable pressure cooker.',
    price: 89,
    category: 'home-appliances',
    image: 'https://cdn.instantpot.com/duo.jpg',
    brand: 'Instant Pot',
    stock: 70,
  },
  {
    name: 'Sony Bravia 75-inch 4K TV',
    description: 'Large screen smart TV with HDR and Android TV.',
    price: 2499,
    category: 'television-accessories',
    image: 'https://cdn.sony.com/bravia-75.jpg',
    brand: 'Sony',
    stock: 20,
  },
  {
    name: 'Samsung Family Hub Refrigerator',
    description: 'Smart refrigerator with touchscreen and voice control.',
    price: 2999,
    category: 'home-appliances',
    image: 'https://cdn.samsung.com/family-hub-fridge.jpg',
    brand: 'Samsung',
    stock: 15,
  },
  {
    name: 'Dyson Pure Cool Air Purifier',
    description: 'Air purifier and fan with HEPA filter.',
    price: 499,
    category: 'home-appliances',
    image: 'https://cdn.dyson.com/pure-cool.jpg',
    brand: 'Dyson',
    stock: 30,
  },
  {
    name: 'Nikon D850 DSLR Camera',
    description: 'High-resolution DSLR with excellent dynamic range.',
    price: 2999,
    category: 'cameras',
    image: 'https://cdn.nikon.com/d850.jpg',
    brand: 'Nikon',
    stock: 25,
  },
  {
    name: 'Canon EOS Rebel T7',
    description: 'Entry-level DSLR camera with 24MP sensor.',
    price: 449,
    category: 'cameras',
    image: 'https://cdn.canon.com/rebel-t7.jpg',
    brand: 'Canon',
    stock: 40,
  },
  {
    name: 'Apple iPad Air',
    description: 'Lightweight tablet with A14 Bionic chip and Retina display.',
    price: 599,
    category: 'electronics',
    image: 'https://cdn.apple.com/ipad-air.jpg',
    brand: 'Apple',
    stock: 90,
  },
  // 90 more unique products here...
];

module.exports = productSeedsPart5;
