const productSeedsPart2 = [
  {
    name: 'Nike Air Max 270',
    description: 'Comfortable and stylish running shoes with Air Max cushioning.',
    price: 150,
    category: 'fashion',
    image: 'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/air-max-270-shoe-KkLcGR.png',
    brand: 'Nike',
    stock: 200,
  },
  {
    name: 'Adidas Ultraboost 21',
    description: 'High-performance running shoes with Boost technology.',
    price: 180,
    category: 'fashion',
    image: 'https://assets.adidas.com/images/w_600,f_auto,q_auto/8a7a7a7a7a7a7a7a7a7a/ultraboost-21-shoes.jpg',
    brand: 'Adidas',
    stock: 150,
  },
  {
    name: 'Levi\'s 501 Original Fit Jeans',
    description: 'Classic straight fit denim jeans with button fly.',
    price: 60,
    category: 'fashion',
    image: 'https://lsco.scene7.com/is/image/lsco/005010114-front-pdp.jpg',
    brand: 'Levi\'s',
    stock: 300,
  },
  {
    name: 'Ray-Ban Wayfarer Sunglasses',
    description: 'Iconic sunglasses with UV protection and classic design.',
    price: 120,
    category: 'fashion',
    image: 'https://images.ray-ban.com/is/image/RayBan/805289126517__001.png',
    brand: 'Ray-Ban',
    stock: 100,
  },
  {
    name: 'Apple Watch Series 7',
    description: 'Smartwatch with health monitoring and fitness tracking.',
    price: 399,
    category: 'electronics',
    image: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/MKMX3_VW_34FR+watch-44-alum-silver-nc-7s_VW_34FR_WF_CO_GEO_IN?wid=940&hei=1112&fmt=png-alpha&.v=1632171067000',
    brand: 'Apple',
    stock: 120,
  },
  {
    name: 'Samsung Galaxy Tab S7',
    description: 'High-end Android tablet with S Pen and 120Hz display.',
    price: 649,
    category: 'electronics',
    image: 'https://images.samsung.com/is/image/samsung/p6pim/in/galaxy-tab-s7/gallery/in-galaxy-tab-s7-t870-sm-t870nznainu-frontmysticbronze-276964973?$720_576_PNG$',
    brand: 'Samsung',
    stock: 80,
  },
  {
    name: 'Sony Alpha a7 III',
    description: 'Full-frame mirrorless camera with 24MP sensor and 4K video.',
    price: 1999,
    category: 'cameras',
    image: 'https://cdn.sony.com/alpha-a7-iii.jpg',
    brand: 'Sony',
    stock: 50,
  },
  {
    name: 'LG 55-inch OLED TV',
    description: 'Stunning OLED display with perfect blacks and vibrant colors.',
    price: 1499,
    category: 'television-accessories',
    image: 'https://www.lg.com/us/images/tvs/md07514604/gallery/desktop-01.jpg',
    brand: 'LG',
    stock: 30,
  },
  {
    name: 'Dyson V11 Torque Drive Vacuum',
    description: 'Cordless vacuum cleaner with powerful suction and long battery life.',
    price: 599,
    category: 'home-appliances',
    image: 'https://dyson.com/v11-vacuum.jpg',
    brand: 'Dyson',
    stock: 40,
  },
  {
    name: 'Philips Airfryer XXL',
    description: 'Healthy cooking with rapid air technology and large capacity.',
    price: 199,
    category: 'home-appliances',
    image: 'https://images.philips.com/is/image/philipsconsumer/airfryer-xxl',
    brand: 'Philips',
    stock: 70,
  },
  // 90 more unique products here...
];

module.exports = productSeedsPart2;
